### ISSUE TITLE
左滑右滑

### ISSUE THREAD

**Issue by liyang521** [liujunliuhong/YHDragContainer#2]
大佬我现在想实现一个效果就是左滑下一张 右滑 滑回上一张 该怎么实现呢 求指导

**Comment by liujunliuhong** [comment]
滑回上一张属于撤销功能，下个版本会加上。同时会提供滑动手势回调，使滑牌更加灵活。如果你等不及，可以改动源码，在pan手势那儿加入自己的逻辑


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by liyang521** [comment]
啥时候更新下一版本呢、🤣

**Comment by liujunliuhong** [comment]
预计端午之后的几天吧

**Comment by liyang521** [comment]
我先试着改下源码 到时候再请教您

**Comment by liujunliuhong** [comment]
可以

**Comment by liyang521** [comment]
有新版本吗 兄dei

**Comment by liujunliuhong** [comment]
周末加上😆

**Comment by liujunliuhong** [comment]
已更新新版本，增加撤销功能。对于你的需求：通过手势来控制撤销功能，我参考了其他应用，比如陌陌，探探，发现撤销功能都是通过某个某个按钮来控制的，因此暂时不实现该功能。如果以后我遇到或者看见其他APP有类似功能，我会增加。Demo已更新，你可以运行查看效果

**Comment by liyang521** [comment]
我想禁用掉左滑优化 只让点按钮滑动改怎么弄

**Comment by liujunliuhong** [comment]
源码里面有个方法addPanGestureForCarView，只需要注释掉该方法里面的内容就可以了。稍后我也会更新pod

**Comment by liyang521** [comment]
嗯 因为我是pod安装的没法改源码😂

**Comment by liujunliuhong** [comment]
@liyang521 OC版本已做了重构，方法发生了一些变化，若还在使用，请更新

**Comment by liyang521** [comment]
好的
