### ISSUE TITLE
可以循环划？？？比如有3张，每次划动，下 面都是3张图，而不是每次都减少的

### ISSUE THREAD

**Issue by mrzhao12** [liujunliuhong/YHDragContainer#3]
可以循环划？？？比如有3张，每次划动，下 面都是3张图，而不是每次都减少的

**Comment by liujunliuhong** [comment]
目前暂不支持
一个折中的办法是：当可见卡片数量开始减少时，重设数据源
目前在进行Swift的重写，重写完成之后，可以考虑无限循环滑动的情况

**Comment by mrzhao12** [comment]
可见卡片数量开始减少时，重设数据源用    [cardContainer reloadData];这个，好像视图也重新加载了，都刷新了

**Comment by mrzhao12** [comment]
可见卡片数量开始减少，是哪一个方法？？

**Comment by liujunliuhong** [comment]
由于并没有考虑无限滑动的情况，所以`reloadData `方法会重新加载视图

此代理是卡片滑出去的回调
```

- (void)cardContainerDidDragOut:(YHDragCardContainer *)cardContainer withDragDirection:(YHDragCardDirection)dragDirection withVerticalDragDirection:(YHDragCardDirection)verticalDragDirection currentCardIndex:(int)currentCardIndex;
```
该回调可获取滑出去的卡片的索引，你可根据滑出去的卡片索引和数据源总数之差来判断可见卡片数量是否减少

**Comment by mrzhao12** [comment]
知道了可见卡片数量减少，然后怎么重设数据源？？？？

**Comment by liujunliuhong** [comment]
😹初始数据源的最后几个移到最前面去就可以了
数据源设置从这个样子
【1，2，3，4，5，6，1，2，3】
当第6个卡片滑出去的时候，reloadData一次，不过这样有点耗内存，数据源少的时候，无所谓了😄

**Comment by mrzhao12** [comment]
不是太理解啊，
初始化数据，只有- (int)numberOfCardWithCardContainer:(YHDragCardContainer *)cardContainer这一个方法啊，需要修改reloadData方法里的源码？？？

**Comment by liujunliuhong** [comment]
举个例子，比如你的datasource有5个model，但是可见卡片有3个，那么你应该把你datasource里面最前的3个model复制一份，放到你的datasource的尾部，此时，你的datasource应该有8个model。
当第5个卡片滑出去(此时第5个卡片对应你的datasource里的第五个model)时，reloadData一次就可以了，这样就给人一种无限滑动的假象

**Comment by mrzhao12** [comment]
意思就是，本来数据只有5个，但是第一次加载数据的时候，在最后添加头3个，形成8个数据，当第5个滑动后，就再次重新加载这8个数据。。。。
大神的想法很六啊，学习了，谢谢🙏

**Comment by liujunliuhong** [comment]
@mrzhao12 OC版本做了重构，若还在使用，请更新
