### ISSUE TITLE
你好，这个最新的支持无限循环滑动的，滑到第三个时，push下一个vc，就复原了到第一个

### ISSUE THREAD

**Issue by mrzhao12** [liujunliuhong/YHDragContainer#4]
滑到第三个卡牌时，卡牌所在的vc有个按钮，点击到下一个vc，再返回，卡片就复原了，是怎么回事？？？

**Comment by long7hao** [comment]
不用划到第三个， 只要你点击的不是第一个卡push的，再返回，卡片都会复原。
#import "YHDragCardContainer.h"
- (void)didMoveToWindow{
    [self reloadData:NO];
}
因为在这个方法里有reload操作

**Comment by liujunliuhong** [comment]
稍后会核实下该问题并更新

**Comment by mrzhao12** [comment]
> 不用划到第三个， 只要你点击的不是第一个卡push的，再返回，卡片都会复原。
> #import "YHDragCardContainer.h"
> 
> * (void)didMoveToWindow{
>   [self reloadData:NO];
>   }
>   因为在这个方法里有reload操作

有啥办法，不让他复原？？？返回后（要保持push跳转前的第3个卡牌）

**Comment by mrzhao12** [comment]
> 稍后会核实下该问题并更新

好的，期待更新

**Comment by liujunliuhong** [comment]
已更新，现在需要自己去reload了，请注意下

**Comment by mrzhao12** [comment]
谢谢了，大神
