### ISSUE TITLE
点击卡片 push 到下一个页面 卡片会自动reload的问题探讨

### ISSUE THREAD

**Issue by long7hao** [liujunliuhong/YHDragContainer#5]
你好，首先感谢你写的这个库😁。

我在使用中发现了个问题 ，当点击卡片 push 到下一个页面  卡片会自动reload。
看了一下代码是因为YHDragCardContainer.h文件里有下面这个方法：
- (void)didMoveToWindow{
    [self reloadData:NO];
}
这里有个reload操作，导致每次显示和不显示卡片的时候都会reload一下；这就导致当点击的不是第一个卡片进行push的时候或者切换到其他页面的时候，卡片都会reload然后显示第一个卡片。

不明白为何要在这里reload，一般来说应该是使用这个库的时候，使用者来主动reload才好。

**Comment by liujunliuhong** [comment]
你好，非常感谢。当初没有做push的测试，感觉不会有问题🤣，没想到会出这么个bug，稍后会核实下该问题并更新

**Comment by mrzhao12** [comment]
> 你好，首先感谢你写的这个库😁。
> 
> 我在使用中发现了个问题 ，当点击卡片 push 到下一个页面 卡片会自动reload。
> 看了一下代码是因为YHDragCardContainer.h文件里有下面这个方法：
> 
> * (void)didMoveToWindow{
>   [self reloadData:NO];
>   }
>   这里有个reload操作，导致每次显示和不显示卡片的时候都会reload一下；这就导致当点击的不是第一个卡片进行push的时候或者切换到其他页面的时候，卡片都会reload然后显示第一个卡片。
> 
> 不明白为何要在这里reload，一般来说应该是使用这个库的时候，使用者来主动reload才好。

我也在用这个，遇到了同样的问题，push 复原

**Comment by mrzhao12** [comment]
> 你好，非常感谢。当初没有做push的测试，感觉不会有问题🤣，没想到会出这么个bug，稍后会核实下该问题并更新

加油

**Comment by liujunliuhong** [comment]
已更新，现在需要自己去reload了，请注意下
