### ISSUE TITLE
当用户快速滑动的时候无法滑动

### ISSUE THREAD

**Issue by changzengjing** [liujunliuhong/YHDragContainer#6]
我看到您在代码设置了userInteractionEnabled为NO，导致了用户每次都等待一会才能滑动，尝试修改却没有改过来 所以放弃了这个库

**Comment by liujunliuhong** [comment]
你好，非常感谢。你说的这个问题其实当初考虑过，之所以加上userInteractionEnabled，是为了避免bug出现，但是确实给人的交互感不是很好，之后的版本会考虑优化这个问题
