### ISSUE TITLE
请问如何支持xib 的cell呢

### ISSUE THREAD

**Issue by lotawei** [liujunliuhong/YHDragContainer#8]

**Comment by lotawei** [comment]
@objc open class YHDragCardCell: UIView {
    @objc public var reuseIdentifier: String = ""
    @objc public init(reuseIdentifier: String) {
        self.reuseIdentifier = reuseIdentifier
        super.init(frame: .zero)
        self.yh_reuseIdentifier = reuseIdentifier
        self.yh_internalIdentifier = UUID().uuidString
        self.yh_is_reuse = false
    }
    
    required public init?(coder: NSCoder) {
        super.init(coder: coder)
    }
}

**Comment by lotawei** [comment]
我将其改造了下看似没啥问题

**Comment by liujunliuhong** [comment]
最开始写这个库的时候，只考虑了纯代码，没有考虑xib。下个版本可以把该功能加上。
