### ISSUE TITLE
数据源只有一条的时候 revoke无法生效

### ISSUE THREAD

**Issue by lotawei** [liujunliuhong/YHDragContainer#9]

**Comment by liujunliuhong** [comment]
已加上该功能，通过设置`canRevokeWhenOnlyOneDataSource`为true即可

**Comment by lotawei** [comment]
thanks



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liujun ***@***.***&gt;
发送时间: 2021年10月22日 14:54
收件人: liujunliuhong/DragCardContainer ***@***.***&gt;
抄送: lotawei ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[liujunliuhong/DragCardContainer] 数据源只有一条的时候 revoke无法生效 (#9)





 
已加上该功能，通过设置canRevokeWhenOnlyOneDataSource为true即可
